[package]
name = "bevy-survivors"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
bevy_ecs_ldtk = "0.10.0"
rand = "0.8.5"

[profile.dev]
opt-level = 1

[profile.dev.packages."*"]
opt-level = 3
